# Basic Python

## 1. Split this string

In [46]:
st = "Hi there Sam!"

In [47]:
out = st.split()
print(out)

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [49]:
pl = "Earth"
di = 12742

In [50]:
print("The diameter of {pl} is {di} kilometesrs".format(pl="Earth",di=12742))

The diameter of Earth is 12742 kilometesrs


## 3. In this nest dictionary grab the word "hello"

In [51]:
dict= {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [52]:
print(dict['k1'][3]['tricky'][3]['target'][3])

hello


# Numpy

In [53]:
import numpy as n

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [54]:
arr = [0] * 10
print (arr)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [55]:
arr1 = [5]*10
print(arr1)

[5, 5, 5, 5, 5, 5, 5, 5, 5, 5]


## 5. Create an array of all the even integers from 20 to 35

In [56]:
import numpy as n
even=n.arange(20,35,2)
print(even)

[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [57]:
import numpy as n
mat =  n.arange(0,9).reshape(3,3)
print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [58]:
import numpy as n
a = n.array([1, 2, 3])
b = n.array([4, 5, 6])
print(n.concatenate((a,b)))

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [61]:
import pandas as p


In [62]:
array=[["d1","d2"],["d3","d4"],["d5","d6"]]
dataframe = p.DataFrame (array,columns=['   column1','   column2'])
print(dataframe)

     column1    column2
0         d1         d2
1         d3         d4
2         d5         d6


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [64]:
import pandas as p
dates = p.date_range('1-1-2023','2-10-2023',freq = 'D')
for val in dates:
  print(val);

2023-01-01 00:00:00
2023-01-02 00:00:00
2023-01-03 00:00:00
2023-01-04 00:00:00
2023-01-05 00:00:00
2023-01-06 00:00:00
2023-01-07 00:00:00
2023-01-08 00:00:00
2023-01-09 00:00:00
2023-01-10 00:00:00
2023-01-11 00:00:00
2023-01-12 00:00:00
2023-01-13 00:00:00
2023-01-14 00:00:00
2023-01-15 00:00:00
2023-01-16 00:00:00
2023-01-17 00:00:00
2023-01-18 00:00:00
2023-01-19 00:00:00
2023-01-20 00:00:00
2023-01-21 00:00:00
2023-01-22 00:00:00
2023-01-23 00:00:00
2023-01-24 00:00:00
2023-01-25 00:00:00
2023-01-26 00:00:00
2023-01-27 00:00:00
2023-01-28 00:00:00
2023-01-29 00:00:00
2023-01-30 00:00:00
2023-01-31 00:00:00
2023-02-01 00:00:00
2023-02-02 00:00:00
2023-02-03 00:00:00
2023-02-04 00:00:00
2023-02-05 00:00:00
2023-02-06 00:00:00
2023-02-07 00:00:00
2023-02-08 00:00:00
2023-02-09 00:00:00
2023-02-10 00:00:00


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [66]:
lst = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [67]:
import pandas as p

dataframe = p.DataFrame(lst, columns = ['c1', 'c2','c3'])

print(dataframe)

   c1   c2  c3
0   1  aaa  22
1   2  bbb  25
2   3  ccc  24
