# Basic Python

## 1. Split this string

In [7]:
s = "Hi there Sam!"

In [8]:
output = s.split()
print(output)

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [9]:
planet = "Earth"
diamtr = 12742

In [10]:
print("The diameter of {planet} is {diamtr} kilometesrs".format(planet="Earth",diamtr=12742))

The diameter of Earth is 12742 kilometesrs


## 3. In this nest dictionary grab the word "hello"

In [11]:
dict = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [12]:
print(dict['k1'][3]['tricky'][3]['target'][3])

hello


# Numpy

In [13]:
import numpy as npy

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [14]:
array = [0] * 10
print (array)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [15]:
arr = [5]*10
print(arr)

[5, 5, 5, 5, 5, 5, 5, 5, 5, 5]


## 5. Create an array of all the even integers from 20 to 35

In [16]:
import numpy as npy
even_int=npy.arange(20,35,2)
print(even_int)

[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [17]:
import numpy as npy
matrix =  npy.arange(0,9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [18]:
import numpy as npy
a = npy.array([1, 2, 3])
b = npy.array([4, 5, 6])
print(npy.concatenate((a,b)))

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [19]:
import pandas as pd


In [20]:
array=[["d1","d2"],["d3","d4"],["d5","d6"]]
dataframe = pd.DataFrame (array,columns=['   column1','   column2'])
print(dataframe)

     column1    column2
0         d1         d2
1         d3         d4
2         d5         d6


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [21]:
import pandas as pd
dates = pd.date_range('1-1-2023','2-10-2023',freq = 'D')
for val in dates:
  print(val);

2023-01-01 00:00:00
2023-01-02 00:00:00
2023-01-03 00:00:00
2023-01-04 00:00:00
2023-01-05 00:00:00
2023-01-06 00:00:00
2023-01-07 00:00:00
2023-01-08 00:00:00
2023-01-09 00:00:00
2023-01-10 00:00:00
2023-01-11 00:00:00
2023-01-12 00:00:00
2023-01-13 00:00:00
2023-01-14 00:00:00
2023-01-15 00:00:00
2023-01-16 00:00:00
2023-01-17 00:00:00
2023-01-18 00:00:00
2023-01-19 00:00:00
2023-01-20 00:00:00
2023-01-21 00:00:00
2023-01-22 00:00:00
2023-01-23 00:00:00
2023-01-24 00:00:00
2023-01-25 00:00:00
2023-01-26 00:00:00
2023-01-27 00:00:00
2023-01-28 00:00:00
2023-01-29 00:00:00
2023-01-30 00:00:00
2023-01-31 00:00:00
2023-02-01 00:00:00
2023-02-02 00:00:00
2023-02-03 00:00:00
2023-02-04 00:00:00
2023-02-05 00:00:00
2023-02-06 00:00:00
2023-02-07 00:00:00
2023-02-08 00:00:00
2023-02-09 00:00:00
2023-02-10 00:00:00


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [22]:
list = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [24]:
import pandas as pd

dataframe = pd.DataFrame(list, columns = ['c1', 'c2','c3'])

print(dataframe)

   c1   c2  c3
0   1  aaa  22
1   2  bbb  25
2   3  ccc  24
