Basic Python


1.Split the string

In [8]:
s = "This is kumar!"
out = s.split()
print(out)

['Hi', 'there', 'Sam!']


2.Use .format() to print the following string.

In [4]:
planet = "Mercury"
diameter = 78654
print("The diameter of {planet} is {diameter} kilometesrs".format(planet="Earth",diameter=12742))

The diameter of Earth is 12742 kilometesrs


3.In this nest dictionary grab the word "hello"

In [3]:
Nest_Dic= {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(Nest_Dic['k1'][3]['tricky'][3]['target'][3])

hello


Numpy

In [7]:
import numpy as np

4.1 Create an array of 10 zeros?

In [1]:
ARR_Z = [0] * 10
print (ARR_Z)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


4.2 Create an array of 10 fives?

In [5]:
ARR_t = [5]*10
print(ARR_t)

[5, 5, 5, 5, 5, 5, 5, 5, 5, 5]


In [6]:
import numpy as np
Array_E=np.arange(20,35,2)
print(Array_E)

[20 22 24 26 28 30 32 34]


In [7]:
import numpy as np
Matrix_three =  np.arange(0,9).reshape(3,3)
print(Matrix_three)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [8]:
import numpy as np
First = np.array([24, 27, 80])
Second = np.array([47, 95, 36])
print(np.concatenate((First,Second)))

[24 27 80 47 95 36]


In [14]:
import pandas as pd

In [16]:
array=[["d1","d2"],["d3","d4"],["d5","d6"]]
dataframe = pd.DataFrame (array,columns=['   column1','   column2'])
print(dataframe)

     column1    column2
0         d1         d2
1         d3         d4
2         d5         d6


In [17]:
import pandas as pd
dates = pd.date_range('1-1-2023','2-10-2023',freq = 'D')
for val in dates:
  print(val);

2023-01-01 00:00:00
2023-01-02 00:00:00
2023-01-03 00:00:00
2023-01-04 00:00:00
2023-01-05 00:00:00
2023-01-06 00:00:00
2023-01-07 00:00:00
2023-01-08 00:00:00
2023-01-09 00:00:00
2023-01-10 00:00:00
2023-01-11 00:00:00
2023-01-12 00:00:00
2023-01-13 00:00:00
2023-01-14 00:00:00
2023-01-15 00:00:00
2023-01-16 00:00:00
2023-01-17 00:00:00
2023-01-18 00:00:00
2023-01-19 00:00:00
2023-01-20 00:00:00
2023-01-21 00:00:00
2023-01-22 00:00:00
2023-01-23 00:00:00
2023-01-24 00:00:00
2023-01-25 00:00:00
2023-01-26 00:00:00
2023-01-27 00:00:00
2023-01-28 00:00:00
2023-01-29 00:00:00
2023-01-30 00:00:00
2023-01-31 00:00:00
2023-02-01 00:00:00
2023-02-02 00:00:00
2023-02-03 00:00:00
2023-02-04 00:00:00
2023-02-05 00:00:00
2023-02-06 00:00:00
2023-02-07 00:00:00
2023-02-08 00:00:00
2023-02-09 00:00:00
2023-02-10 00:00:00


In [18]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]



In [19]:

dataframe = pd.DataFrame(lists, columns = ['c1', 'c2','c3'])

print(dataframe)

   c1   c2  c3
0   1  aaa  22
1   2  bbb  25
2   3  ccc  24
